In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [3]:
# Set seed pentru reproducibilitate
np.random.seed(42)

# Număr de înregistrări
n = 100

In [9]:
# Generare date sintetice
data = {
    'ID': range(1, n+1),
    
    # Caracteristici demografice
    'Varsta': np.random.randint(18, 70, n),
    'Sex': np.random.choice(['Masculin', 'Feminin'], n, p=[0.48, 0.52]),
    'Tip_Localitate': np.random.choice(['Urban', 'Rural'], n, p=[0.65, 0.35]),
    
    # Variabile principale
    'Tip_Cafea_Preferat': np.random.choice(
        ['Espresso', 'Latte', 'Americano', 'Cappucino', 'Decaf', 'Alte'], 
        n, 
        p=[0.25, 0.20, 0.28, 0.20, 0.05, 0.02]
    ),
    
    'Numar_Cani_Pe_Zi': np.random.choice(
        [1, 2, 3, 4, 5], 
        n, 
        p=[0.20, 0.35, 0.25, 0.15, 0.05]
    ),
    
    'Ora_Consum_Dominanta': np.random.choice(
        ['Dimineata', 'Pranz', 'Seara'], 
        n, 
        p=[0.65, 0.25, 0.10]
    ),
    
    'Buget_Luna_MDL': np.random.randint(200, 2000, n),
    
    'Loc_Achizitie': np.random.choice(
        ['Cafenea', 'Supermarket', 'Oficiu', 'Distributie_Automata', 'Acasa_Boabe', 'Alte'],
        n,
        p=[0.25, 0.20, 0.20, 0.20, 0.10, 0.05]
    ),
}

In [10]:
# Creare DataFrame
df = pd.DataFrame(data)

# Ajustări logice pentru coerență
# Persoanele mai tinere tind să consume mai mult latte
df.loc[(df['Varsta'] < 30) & (np.random.rand(n) < 0.4), 'Tip_Cafea_Preferat'] = 'Latte'

# Persoanele mai în vârstă tind să consume mai mult decaf
df.loc[(df['Varsta'] > 55) & (np.random.rand(n) < 0.3), 'Tip_Cafea_Preferat'] = 'Decaf'

# Urban tinde să aibă buget mai mare
urban_mask = df['Tip_Localitate'] == 'Urban'
df.loc[urban_mask, 'Buget_Luna_MDL'] = (
    df.loc[urban_mask, 'Buget_Luna_MDL'] * np.random.uniform(1.1, 1.3, sum(urban_mask))).astype(int)

df.head(5)

,ID,Varsta,Sex,Tip_Localitate,Tip_Cafea_Preferat,Numar_Cani_Pe_Zi,Ora_Consum_Dominanta,Buget_Luna_MDL,Loc_Achizitie
0,1,67,Masculin,Urban,Espresso,2,Pranz,273,Acasa_Boabe
1,2,22,Feminin,Urban,Latte,3,Dimineata,1891,Acasa_Boabe
2,3,47,Feminin,Urban,Cappucino,4,Dimineata,838,Cafenea
3,4,41,Masculin,Urban,Cappucino,2,Dimineata,328,Oficiu
4,5,20,Feminin,Rural,Americano,4,Dimineata,1025,Alte

In [18]:
# Salvare în CSV
df.to_csv('./dataset/date_cafea_consum.csv', index=False, encoding='utf-8-sig')

print("✓ Fișier CSV generat cu succes: date_cafea_consum.csv")
print(f"\n📊 Statistici generale:")
print(f"   - Total înregistrări: {len(df)}")
print(f"   - Vârstă medie: {df['Varsta'].mean():.1f} ani")
print(f"   - Consum mediu zilnic: {df['Numar_Cani_Pe_Zi'].mean():.2f} căni")
print(f"   - Buget mediu lunar: {df['Buget_Luna_MDL'].mean():.2f} MDL")
print(f"\n📋 Primele 5 înregistrări:")
# print example of table
# pandas settings
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.display.width = 0
df.head(5)

✓ Fișier CSV generat cu succes: date_cafea_consum.csv

📊 Statistici generale:
   - Total înregistrări: 100
   - Vârstă medie: 46.2 ani
   - Consum mediu zilnic: 2.75 căni
   - Buget mediu lunar: 1209.60 MDL

📋 Primele 5 înregistrări:

,ID,Varsta,Sex,Tip_Localitate,Tip_Cafea_Preferat,Numar_Cani_Pe_Zi,Ora_Consum_Dominanta,Buget_Luna_MDL,Loc_Achizitie
0,1,67,Masculin,Urban,Espresso,2,Pranz,273,Acasa_Boabe
1,2,22,Feminin,Urban,Latte,3,Dimineata,1891,Acasa_Boabe
2,3,47,Feminin,Urban,Cappucino,4,Dimineata,838,Cafenea
3,4,41,Masculin,Urban,Cappucino,2,Dimineata,328,Oficiu
4,5,20,Feminin,Rural,Americano,4,Dimineata,1025,Alte